name: flutter_demos
description: A new Flutter project.
# A linha a seguir evita que o pacote seja acidentalmente publicado no
# pub.dev usando `flutter pub publish`. Isso é preferido para pacotes privados.
publish_to: 'none' # Remova esta linha se desejar publicar em pub.dev

# O seguinte define a versão e o número de compilação para seu aplicativo.
# Um número de versão são três números separados por pontos, como 1.2.43
# seguido por um número de compilação opcional separado por um +.
# Tanto a versão quanto o número do construtor podem ser substituídos em flutter
# build especificando --build-name e --build-number, respectivamente.
# No Android, build-name é usado como versionName enquanto build-number é usado como versionCode.
# Leia mais sobre o versionamento do Android em https://developer.android.com/studio/publish/versioning
# No iOS, build-name é usado como CFBundleShortVersionString enquanto build-number é usado como CFBundleVersion.
# Leia mais sobre versionamento do iOS em
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# No Windows, build-name é usado como as partes principais, secundárias e de patch
# das versões do produto e do arquivo enquanto o número da compilação é usado como o sufixo da compilação.
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

# As dependências especificam outros pacotes que seu pacote precisa para funcionar.
# Para atualizar automaticamente suas dependências de pacote para as versões mais recentes
# considere executar `flutter pub upgrade --major-versions`. Alternativamente,
# dependências podem ser atualizadas manualmente alterando os números de versão abaixo para
# a versão mais recente disponível em pub.dev. Para ver quais dependências têm mais novas
# versões disponíveis, execute `flutter pub desatualizado`.
dependencies:
  flutter:
    sdk: flutter

  # O seguinte adiciona a fonte Cupertino Icons ao seu aplicativo.
  # Use com a classe CupertinoIcons para ícones de estilo iOS.
  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.4.1
  google_fonts: ^3.0.1
  animate_do: ^3.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  # O pacote "flutter_lints" abaixo contém um conjunto de lints recomendados para
  # encorajar boas práticas de codificação. O conjunto de fiapos fornecido pelo pacote é
  # ativado no arquivo `analysis_options.yaml` localizado na raiz do seu
  # pacote. Consulte esse arquivo para obter informações sobre como desativar o lint específico
  # regras e ativando outras adicionais.
  flutter_lints: ^2.0.0

# Para obter informações sobre a parte genérica Dart deste arquivo, consulte o
# página a seguir: https://dart.dev/tools/pub/pubspec

# A seção a seguir é específica para pacotes Flutter.
flutter:

  # A linha a seguir garante que a fonte Material Icons seja
  # incluído em seu aplicativo, para que você possa usar os ícones em
  # a classe Material Icons.
  uses-material-design: true

  assets:
     - assets/images/
  
  # Um recurso de imagem pode se referir a uma ou mais "variantes" específicas de resolução, consulte
  # https://flutter.dev/assets-and-images/#resolution-aware

  # Para obter detalhes sobre a adição de ativos de dependências de pacote, consulte
  # https://flutter.dev/assets-and-images/#from-packages

  # Para adicionar fontes personalizadas ao seu aplicativo, adicione uma seção de fontes aqui,
  # nesta seção "flutter". Cada entrada nesta lista deve ter um
  # tecla "family" com o nome da família da fonte, e uma tecla "fonts" com um
  # lista fornecendo o recurso e outros descritores para a fonte. Para
  # exemplo:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # Para detalhes sobre as fontes das dependências do pacote,
  # consulte https://flutter.dev/custom-fonts/#from-packages
